"""stabilize lead inbox ordering

Revision ID: 1bb2e54cc247
Revises: 10b163b2807f
Create Date: 2026-09-08 21:31:20.531435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb2e54cc247'
down_revision: Union[str, Sequence[str], None] = '10b163b2807f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_created_at_desc'), table_name='leads')
    op.create_index('ix_leads_created_at_id_desc', 'leads', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_created_at_id_desc', table_name='leads')
    op.create_index(op.f('ix_leads_created_at_desc'), 'leads', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
